version: "3.9"

services:
  api-server:
    image: sagra-time-api-server:1.0-SNAPSHOT
    ports:
      - "8080:81"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=example
      - DB_PASSWORD=example
      - DB_NAME=exampledb

  webapp-server:
    image: sagra-time-webapp-server:1.0-SNAPSHOT
    ports:
      - "8080:80"
    depends_on:
      - api-server
    environment:
      - API_SERVER_URL=http://api-server:8080

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
